### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by marians**
- remove `dstat`, which is no longer available
- Update mirror URL for testing packages
- Add kubectl
- Merge all install commands into one RUN

### CODE REVIEW

**Comment by marians** [comment]
@pipo02mix I'm thinking that we could use this one instead of the `teemow/debug` for app-updater. Do you know of any other dependency we would need?

**Comment by marians** [comment]
@pipo02mix Seems like all dependencies are met. app-updater does it's job, at least in the case where no update is needed.

**Comment by pipo02mix** [comment]
The only one comes to my mind is `git` but I guess it is there already

**Review by pipo02mix — APPROVED** [review]

**Comment by marians** [comment]
Yes, git is included

**Pull request merged**
